// Semester dates in YYYY-MM-DD format.
const SEMESTER_START = '2026-09-14';
const SEMESTER_END = '2026-12-14';

function setupMenu() {
    const button = document.querySelector('.menu-toggle');
    const menu = document.querySelector('.main-nav');
    button.onclick = function () {
        menu.classList.toggle('is-open');
        button.setAttribute('aria-expanded', menu.classList.contains('is-open'));
    };
}

function setupSchedule() {
    if (!document.querySelector('.schedule-table')) return;
    const lessons = document.querySelectorAll('.class-cell');
    const buttons = document.querySelectorAll('.filter-button');
    const status = document.querySelector('#lesson-status');
    const days = ['pondelok', 'utorok', 'stredu', 'štvrtok', 'piatok', 'sobotu', 'nedeľu'];

    for (const button of buttons) {
        button.onclick = function () {
            let count = 0;
            for (const lesson of lessons) {
                const show = button.dataset.filter === 'all' || lesson.classList.contains(button.dataset.filter);
                lesson.classList.toggle('filtered-out', !show);
                if (show) count++;
            }
            for (const other of buttons) {
                other.classList.toggle('active', other === button);
                other.setAttribute('aria-pressed', other === button);
            }
            document.querySelector('#filter-status').textContent = '';
            if (count === 0) document.querySelector('#filter-status').textContent = 'Pre tento filter nemám žiadne hodiny.';
        };
    }

    function updateLesson() {
        const now = new Date();
        const weekDay = (now.getDay() + 6) % 7;
        const time = weekDay * 1440 + now.getHours() * 60 + now.getMinutes();
        let current = null;
        let next = null;
        let wait = 10081;
        for (const lesson of lessons) {
            const day = Number(lesson.dataset.day) - 1;
            const start = day * 1440 + Number(lesson.dataset.start) * 60;
            const end = day * 1440 + Number(lesson.dataset.end) * 60;
            const active = time >= start && time < end;
            lesson.classList.toggle('current-lesson', active);
            if (active) current = lesson;
            let difference = start - time;
            if (difference <= 0) difference += 10080; // Minutes in one week.
            if (difference < wait) {
                wait = difference;
                next = lesson;
            }
        }
        status.textContent = 'V rozvrhu nemám žiadne hodiny.';
        if (next) status.textContent = 'Teraz nemám výučbu. Najbližšie mám ' + next.textContent.trim() + ' v ' + days[next.dataset.day - 1] + ' o ' + next.dataset.start + ':00.';
        if (current) status.textContent = 'Práve mám: ' + current.textContent.trim() + '.';
    }

    updateLesson();
    setInterval(updateLesson, 60000);

    updateSemester();
    setInterval(updateSemester, 60000);
}

function updateSemester() {
    const start = new Date(SEMESTER_START + 'T00:00:00');
    const end = new Date(SEMESTER_END + 'T23:59:59');
    const today = new Date();
    const totalTime = end - start;
    const elapsedTime = today - start;
    let percent = Math.round(elapsedTime / totalTime * 100);

    if (percent < 0) percent = 0;
    if (percent > 100) percent = 100;

    document.querySelector('#semester-percent').textContent = percent + ' %';
    document.querySelector('#progress-bar').style.width = percent + '%';
    document.querySelector('#semester-progress').setAttribute('aria-valuenow', percent);
    document.querySelector('#semester-dates').textContent = 'Semester: ' + start.toLocaleDateString('sk-SK') + ' – ' + end.toLocaleDateString('sk-SK');
}

async function setupWeather() {
    const weather = document.querySelector('#weather');
    if (!weather) return;
    try {
        const response = await fetch('https://api.open-meteo.com/v1/forecast?latitude=48.153&longitude=17.073&current=temperature_2m,wind_speed_10m,relative_humidity_2m');
        if (!response.ok) throw new Error('Weather request failed');
        const data = await response.json();
        const current = data.current;
        weather.textContent = 'Teplota: ' + current.temperature_2m + ' °C. Vietor: ' + current.wind_speed_10m + ' km/h. Vlhkosť: ' + current.relative_humidity_2m + ' %.';
    } catch (error) {
        weather.textContent = 'Počasie sa nepodarilo načítať. Skús obnoviť stránku.';
    }
}

// Generated by AI: OpenAI Codex. Reviewed and adapted for this assignment.
function setupMap() {
    if (!document.querySelector('#leaflet-map')) return;
    const result = document.querySelector('#distance-result');
    if (typeof L === 'undefined') {
        result.textContent = 'Mapu sa nepodarilo načítať. Skontroluj pripojenie a obnov stránku.';
        return;
    }
    const points = {
        home: {name: 'ŠD Mladosť, Staré grunty 53', lat: 48.158674, lon: 17.064139},
        school: {name: 'FEI STU', lat: 48.153, lon: 17.073}
    };
    const select = document.querySelector('#point-select');
    const target = document.querySelector('#target-select');
    const message = document.querySelector('#map-empty');
    const markers = {};
    const map = L.map('leaflet-map').setView([48.156, 17.068], 14);
    const color = getComputedStyle(document.documentElement).getPropertyValue('--accent').trim();
    const line = L.polyline([], {color: color}).addTo(map);
    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
    }).addTo(map);

    function popup(text) {
        const element = document.createElement('span');
        element.textContent = text;
        return element;
    }

    function addMarker(id) {
        const point = points[id];
        markers[id] = L.marker([point.lat, point.lon]).addTo(map).bindPopup(popup(point.name));
    }

    function addPoint(point) {
        points[point.id] = point;
        select.add(new Option(point.name, point.id));
        const item = document.createElement('li');
        item.textContent = point.name;
        document.querySelector('#point-list').append(item);
        addMarker(point.id);
        message.textContent = 'Vlastné body vyberieš zo zoznamu. Ďalší pridáš kliknutím do mapy.';
    }

    addMarker('home');
    addMarker('school');
    let saved = [];
    try {
        const stored = JSON.parse(localStorage.getItem('postaichuk-map-points') || '[]');
        if (!Array.isArray(stored)) throw new Error('Invalid saved points');
        for (const point of stored) {
            if (!point || typeof point.id !== 'string' || !point.id.startsWith('point-')) continue;
            if (typeof point.name !== 'string' || !Number.isFinite(point.lat) || !Number.isFinite(point.lon)) continue;
            saved.push(point);
            addPoint(point);
        }
    } catch (error) {
        message.textContent = 'Uložené body sa nepodarilo načítať. Nový bod pridáš kliknutím do mapy.';
    }
    map.on('click', function (event) {
        const name = prompt('Ako sa má nový bod volať?');
        if (!name || !name.trim()) return;
        const point = {id: 'point-' + Date.now(), name: name.trim(), lat: event.latlng.lat, lon: event.latlng.lng};
        saved.push(point);
        addPoint(point);
        select.value = point.id;
        updateDistance();
        markers[point.id].openPopup();
        try {
            localStorage.setItem('postaichuk-map-points', JSON.stringify(saved));
        } catch (error) {
            message.textContent = 'Bod je na mape, ale prehliadač ho nedovolil uložiť po obnovení stránky.';
        }
    });

    function updateDistance() {
        const from = points[select.value];
        const to = points[target.value];
        for (const id in markers) markers[id].setPopupContent(popup(points[id].name));
        if (select.value === target.value) {
            result.textContent = 'Vyber dva rozdielne body.';
            line.setLatLngs([]);
            return;
        }
        const distance = haversine(from.lat, from.lon, to.lat, to.lon).toFixed(2);
        result.textContent = 'Vzdušná vzdialenosť: ' + distance + ' km.';
        line.setLatLngs([[from.lat, from.lon], [to.lat, to.lon]]);
        markers[select.value].setPopupContent(popup(from.name + ' → ' + to.name + ': ' + distance + ' km'));
        markers[target.value].setPopupContent(popup(to.name + ' → ' + from.name + ': ' + distance + ' km'));
    }

    select.onchange = updateDistance;
    target.onchange = updateDistance;
    updateDistance();
}

function toRadians(degrees) {
    return degrees * Math.PI / 180;
}

// Generated by AI: OpenAI Codex. Reviewed and adapted for this assignment.
// Haversine formula: straight-line distance on Earth in kilometres.
function haversine(lat1, lon1, lat2, lon2) {
    const latitude = toRadians(lat2 - lat1);
    const longitude = toRadians(lon2 - lon1);
    const a = Math.sin(latitude / 2) ** 2 + Math.cos(toRadians(lat1)) * Math.cos(toRadians(lat2)) * Math.sin(longitude / 2) ** 2;
    return 6371 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

console.info('Generated by AI: OpenAI Codex');
setupMenu();
setupSchedule();
setupWeather();
setupMap();
